#!/bin/sh
split_slash () {
  local IFS=/
  read $@
}

cat $CHROMENV_HOME/master/google-chrome/versions/mac
# while split_slash VERSION FILENAME; do
#   echo $VERSION
# done < $CHROMENV_HOME/master/chromedriver/versions/mac64
