#!/bin/sh
touch $CHROMENV_ROOT/default_version
NOW_VERSION=$(cat $CHROMENV_ROOT/default_version)
if [ -z $NOW_VERSION ];
then
  ls -1 $CHROMENV_ROOT/versions | xargs -I {} echo "  {}"
else
  ls -1 $CHROMENV_ROOT/versions | xargs -I {} echo "  {}" | sed "s/  $NOW_VERSION/* $NOW_VERSION/g"
fi
